runtime: nodejs12

env_variables:
  PRODUCTION: true

basic_scaling:
  max_instances: 11

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
